# Generated by Django 4.1.3 on 2022-12-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifoliobase', '0002_project_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=1500)),
            ],
        ),
    ]
