# Generated by Django 4.1.3 on 2022-12-09 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifoliobase', '0003_contato'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contato',
            new_name='Contact',
        ),
    ]
